version: 0.0
os: linux

files:
  - source: target/Ecomm.war
    destination: /home/ec2-user/

hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: root

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/copy_war.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
