version: 0.0
os: linux
files:
  - source: target/Ecomm.war
    destination: /home/ec2-user/
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user

