version: 0.0
os: linux

files:
  - source: Ecomm.war
    destination: /home/ec2-user/
  - source: tomcat-users.xml
    destination: /home/ec2-user/

hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ec2-user
    - location: scripts/install_tomcat.sh
      timeout: 600
      runas: ec2-user

  AfterInstall:
    - location: scripts/configure_tomcat.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/deploy_war.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 120
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
