version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing tools..."
      - yum install -y wget tar

  pre_build:
    commands:
      - echo "Downloading Ecomm.war from S3..."
      - aws s3 cp s3://war-tomcat/Ecomm.war ./Ecomm.war

  build:
    commands:
      - echo "Preparing artifact bundle..."

artifacts:
  files:
    - Ecomm.war
    - appspec.yml
    - scripts/**
    - tomcat-users.xml
