version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
  pre_build:
    commands:
      - echo "Checking Maven version..."
      - mvn --version
  build:
    commands:
      - echo "Building the WAR file..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      - ls -l target

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - tomcat-users.xml
    - target/*.war
  discard-paths: yes
