version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo "Running Maven build..."
      - mvn clean package
artifacts:
  files:
    - target/Ecomm.war
    - appspec.yml
    - scripts/install_and_deploy_tomcat.sh
    - tomcat-users.xml
