version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
  pre_build:
    commands:
      - echo "Checking Maven version..."
      - mvn --version
  build:
    commands:
      - echo "Building WAR package..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Copying WAR to root for CodeDeploy..."
      - cp target/Ecomm.war .
      - ls -l

artifacts:
  files:
    - Ecomm.war
    - appspec.yml
    - scripts/**
    - tomcat-users.xml
