name: deply EcommApp
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chechout@v4
    - name: Setup jdk 17
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        disturbution: 'tumurin'
        cache: maven
    - name: Build with maven
      run: mvn -B package --file pom.xml
      
