name: Launch EC2 Instance

on:
  workflow_dispatch:  # This lets you run it manually from GitHub Actions tab

jobs:
  launch:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0861f4e788f5069dd \
            --instance-type t2.micro \
            --key-name ec2console \
            --security-group-ids sg-0b74ceb61cfacb89a \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHub-EC2}]'
