name: Launch EC2 Instance

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 Instance
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ami-0b982602dbb32c5bd \
          --count 1 \
          --instance-type t2.micro \
          --key-name ec2launch \
          --security-group-ids sg-00521d3d29b30c582 \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "Launched EC2 Instance ID: $INSTANCE_ID"
